class RequestModel:
    nome = ""
    email = ""
    cpf = ""
    telefone = ""
    rua = ""
    bairro = ""
    cidade = ""
    estado = ""
    cep = ""
    data_de_nascimento = ""
    produto = ""
    restringido = ""
    bloqueado = ""
    user_agent = ""
    imei = ""
